version: "3.8"

services:
  app:
   depends_on:
    - mysqldb
    - myredis
   build: .
   restart: on-failure
   env_file: ./.env
   ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
   environment:
    - MYSQL_HOST=mysqldb
    - MYSQL_PORT=$MYSQLDB_DOCKER_PORT
    - MYSQL_DATABASE=$MYSQLDB_DATABASE
    - MYSQL_USER=$MYSQLDB_USER
    - MYSQL_PASSWORD=$MYSQLDB_ROOT_PASSWORD
    - REDIS_HOST=myredis
    - REDIS_PORT=$REDIS_DOCKER_PORT

  myredis:
    container_name: myredis
    image: redis:latest
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $REDIS_LOCAL_PORT:$REDIS_DOCKER_PORT
    volumes:
      - redisvol:/data
    command: redis-server --port $REDIS_DOCKER_PORT

  mysqldb:
    container_name: mysqldb
    image: mysql:latest
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - mysqlvol:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
      - MYSQL_TCP_PORT=$MYSQLDB_DOCKER_PORT
   
volumes:
  mysqlvol:
  redisvol: